apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: flink-example-policy
  namespace: default
spec:
  resourceSelectors:
    - apiVersion: flink.apache.org/v1beta1
      kind: FlinkDeployment
      labelSelector:
        matchLabels:
          app: flink-app
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
        - member3
        